name: Fontship

on: [push, pull_request]

jobs:

  fontship:
    name: Fontship
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Fetch tags
        run: |
          git fetch --prune --tags ||:
      - name: Fontship make
        uses: theleagueof/fontship@v0
        # Work around fontship v0.10.0 an below trying to force install-dist on first pass
        with:
          args: make debug all
      - name: FontProof
        id: fontproof
        uses: sile-typesetter/fontproof@v2
        with:
          args: documentation/waterfalls.sil -o documentation/waterfalls.pdf
      - name: SILE
        id: sile
        uses: sile-typesetter/sile@v0
        with:
          args: --version; pacman --noconfirm -Sq tex-gyre-fonts; sile documentation/sample.sil
      - name: Fontship package
        id: fontship
        uses: theleagueof/fontship@v0
        with:
          args: make dist
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.fontship.outputs.DISTDIR }}
          path: ${{ steps.fontship.outputs.DISTDIR }}.zip
      - name: Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ steps.fontship.outputs.DISTDIR }}.zip
            ${{ steps.fontship.outputs.DISTDIR }}.tar.zst
        env:
          GITHUB_TOKEN: ${{ github.token }}
